### PR TITLE
Add kqlDatabase as resource, implement nested json body in request, change readme

### PR DESCRIPTION
**Pull request by FakieHeelflip**
- add kqlDatabase as new resource --> tested locally: create, read, update, delete 
- change map[string]string to map[string]interface{} in all http request functions to make nested json body possible
- changed readme

### CODE REVIEW

**Comment by FakieHeelflip** [comment]
oh, i missed the documentation for kqlDatabases :-/

**Comment by ChristopherNagl** [comment]
can you include an example under examples/resources? Or just add one here as a comment and i do it

**Comment by FakieHeelflip** [comment]
add the example resource

**Comment by ChristopherNagl** [comment]
lgtm

**Pull request merged**
